### ISSUE TITLE
using @include in CSS will cause classes to be an empty object

### ISSUE THREAD

**Issue by HaiRongHaHA** [mrmckeb/typescript-plugin-css-modules#146] opened 2021-10-21 04:16 UTC
Hello, when I using @include in CSS will cause classes to be an empty object, as shown in the following figure

![image](https://user-images.githubusercontent.com/34539325/138209245-f53fb48a-e25a-4568-9894-a1c3f3b54dd9.png)

Just remove @include

![image](https://user-images.githubusercontent.com/34539325/138209318-3ec3b5f9-70e0-45d3-a0e2-505350fb2304.png)

Maybe it's because mine @mixin  is global
// vite.config.ts
![image](https://user-images.githubusercontent.com/34539325/138210372-96ff782a-53c8-4c26-81aa-a60ebdee571c.png)

**Comment by xeho91** [comment] 2021-11-15 06:36
I am facing a similar issue.
When a CSS module file contains those "at-rules": `@use`, `@include`, and `@apply` _(from the TailwindCSS)_.

It returns an error `Property '<specific class name>' does not exist on type {}`.

My `tsconfig.json` contains the following setup:
```json
"plugins": [
  {
    "name": "typescript-plugin-css-modules",
    "options": {
      "sass": {
        "rendererOptions": {
          "includePaths": ["src/styles"]
        }
      }
    }
  }
]
```

@mrmckeb Could I ask for guidance on how I could debug it, to figure out why it can't resolve these "at-rules"?

**Comment by tleunen** [comment] 2021-11-16 05:42
Having the same issue currently. Interesting in finding a solution without moving back to relative paths

**Comment by kontuljan** [comment] 2021-11-18 13:29
I am facing a similar issue as well (using @use).

When I reference some .scss file by relative path, everythig works fine.
![image](https://user-images.githubusercontent.com/38462237/142422421-4a355eab-6f72-4b68-8e30-f539335f923f.png)
![image](https://user-images.githubusercontent.com/38462237/142422857-38693970-c2e8-4eca-b06b-daee25d47fc1.png)


But, when I reference same file absolutely, like this:
![image](https://user-images.githubusercontent.com/38462237/142422514-d866cc60-e78a-4074-a77d-b75dfdde2a97.png)
with tsconfig's "includePaths" set
![image](https://user-images.githubusercontent.com/38462237/142423650-9bb25f58-5930-4c3b-87c0-3cb8b6792e73.png)

or like that:
![image](https://user-images.githubusercontent.com/38462237/142422574-dd6c1081-0f9b-4fd3-a577-937f116b0d76.png)
[FYI: [it is possible to reference root dir this way](https://stackoverflow.com/a/64034825/1789055)]

**I am facing issue described in this thread.**
![image](https://user-images.githubusercontent.com/38462237/142422644-f3d55fd4-5b72-4ac2-8aaa-14282d1219bc.png)

Meaning, I have no intellisense with class names, and VSCode shows error (but I can compile code anyway).

**Comment by tleunen** [comment] 2021-11-30 22:17
So I was able to get it fixed by using an absolute path in `includePaths`, but it's far from being a great solution.

Can we have someone looking into it? `tsconfig` cannot be in JS so converting the relative path into an absolute path should be easily doable within this plugin... If that's the right fix.
The tests all use `__dirname`, which is an absolute path as well, so it could explain why tests are passing, but not for different projects using this sass option `includePaths`

Looks like some work to transform the relative path into an absolute based on the working directory would be required here https://github.com/mrmckeb/typescript-plugin-css-modules/blob/82ba03548c3d2193508e1a4dbc47c1aa9b22943c/src/helpers/getClasses.ts#L91

cc @mrmckeb

**Comment by kontul-dev** [comment] 2021-12-09 11:58
@tleunen : could you share your solution? 

I am not able to make it work (by defining absolute path to "/src").

**Comment by tleunen** [comment] 2021-12-09 15:59
It's not really a solution though.

I was simply able to make it work by using an absolute path in my tsconfig file.
For example:
```
"includePaths": ["/Users/xxx/projects/yyy/src"]
```

**Comment by kontul-dev** [comment] 2021-12-09 16:09
@tleunen Thanks for quick response. I just wanted to try it as temporary solution.

Anyway, I can add another piece of information - it doesn't seem to work on Windows, like:

`"includePaths": ["C:\\PROJECTS\\xyz\\src"] `

(neither with / as path separator)

**Comment by mrmckeb** [comment] 2022-01-05 00:27
Sorry for the slow reply, I was moving country (back in Australia now) and obviously that's eaten a lot of my time.

Can someone provide a very simple reproduction for me? I can then use that to debug against and will provide a solution.

**Comment by falahati** [comment] 2022-01-05 16:56
there is a similar problem with `less`. If the path is specified with a leading dash it fails. Meaning that:

`@import "src/themes/_colors.less";`
works and VSCode provide type completion inside of the `ts` file, but VSCode does not offer completion inside of the `less` file.

but,
`@import "/src/themes/_colors.less";`
breaks this plugin and therefore the returned import contains `{}`, but vscode is able to navigate to the imported less file, and variable and code completion works inside of the `less` file.

So there is no way to have VS work as expected in both files unless a relative path is used which is a pain for styling files.

**Comment by falahati** [comment] 2022-01-06 15:50
another interesting fact is that with NextJS, using relative addresses (or absolute without the leading slash) would result in warnings regarding caching issues so even this workaround probably won't work as well as I expected.

**Comment by leozhao0709** [comment] 2022-01-07 01:38
Seeing the similar thing in scss file.

If `@import relativePath` in scss file, it work correctly. But when it use `@import aliasPath` (alias path defined in tsconfig file), then it stop working. And intellisense just gives an empty object.

**Comment by mthines** [comment] 2022-01-13 09:00
@mrmckeb 

> Sorry for the slow reply, I was moving country (back in Australia now) and obviously that's eaten a lot of my time.
> 
> Can someone provide a very simple reproduction for me? I can then use that to debug against and will provide a solution.

Look here for examples to reproduce. I wasn't able to get it working properly in a CodeSandbox so you have to try in your own environment.

https://github.com/mrmckeb/typescript-plugin-css-modules/issues/152

**Comment by tleunen** [comment] 2022-02-11 15:16
@mrmckeb Was the info I provided enough for you to be able to test this?
I have sass files which uses "absolute" paths so I can avoid having a relative path hell. I have that setup with my sass loader in webpack as well so it all works great.
Here's an example of a file with import/include statements
```sass
@import "sass/mixins/xyz";
.row {
  @include rowContainer;
  // ...
}
```

The directory `sass` is at the root of my project.

in my TSconfig, it requires me to put an absolute path, which is not great because the path is different for all devs. Simply using `./` doesn't work.

```
"rendererOptions": {
  "sass": {
    "includePaths": ["/Users/xxxx/projects/yyyy/"]
  }
}
```

The ts plugin must ran from the same directory as the sass file, which is why using `./` doesn't work? Anyway to make all of provided custom `includePaths` relative to the root of the project, or the tsconfig file? 
Afaik, tsconfig must be in JSON, so there's no way to use some JS magic to make it work by ourselves.
Another way would be to introduce another option to the plugin, such as `rootDir` maybe?

**Comment by philjones88** [comment] 2022-04-04 15:33
Also hitting this issue, a bit more complexity to add to the potential solution is supporting TS types:

i.e. in the `Foo.module.scss` we have:

```
@import '@/Mixins/Mixins.scss';

.foo {
  @include flex(flex, flex-start, center);

  ......
}
```

and in our tsconfig.json:

```
  "paths": {
      "@/*": ["src/*"]
    },
```

**Comment by kirill-martynov** [comment] 2022-07-01 10:58
Hello!

Does anyone found a solution for this?
Struggling with same issue, when using global scss variables in *.module.scss I'm getting `{}` empty type
<img width="442" alt="Screenshot 2022-07-01 at 13 57 51" src="https://user-images.githubusercontent.com/70448489/176881718-b12741af-9858-4183-8d29-7dfc965564cc.png">

**Comment by wp993080086** [comment] 2022-07-21 04:15
**目前在xxx.module.scss中，使用@include是不支持的，会导致获得空对象**

以下写法可行：
![QQ截图20220721120146](https://user-images.githubusercontent.com/52116404/180127914-cb9d464b-c34a-4480-a260-4a2f5606a158.png)
![QQ截图20220721120208](https://user-images.githubusercontent.com/52116404/180128339-bd1d5544-67af-4fed-a337-f75b6cb3750e.png)

![QQ截图20220721120244](https://user-images.githubusercontent.com/52116404/180128511-b37bc147-4955-4b36-b303-318f4798cdba.png)

**Comment by PodaruDragos** [comment] 2022-10-17 15:14
@mrmckeb hello.
my apologies for tagging you like this, but did you happen to have a bit of spare time to merge the PR's that fixes this problem ?

**Comment by falahati** [comment] 2022-10-18 15:16
I have pushed an MR to solve this problem with absolute paths. you can check it out before it gets merged (if it ever gets merged) by replacing the current version of the library to:
```bash
npm install --save-dev github:falahati/typescript-plugin-css-modules#main --ignore-scripts --no-optional
```

What it does is that it adds the current `.tsconfig` directory as the base path of both `less` and `scss` renderers. effectively allowing files to be included from the root of the project. This works with my setup using `less` and NextJs providing IntelliSense both inside the `less` file and on the `tsx` file with no warning on the NextJs's webpack compilation process. hope it helps someone.

**Closed** 2022-12-04 01:29 UTC
Labels: enhancement

**Comment by tleunen** [comment] 2022-12-06 16:09
Since it's based automatically on the directory where the `tsconfig` lives, I don't think this solution works well when the project contains many different tsconfigs files.

But even if I remove or change the abs paths, I can't find any way to make it work.

I think the only good fix for this issue is to fix the `includePaths` option as I mentioned in [this comment](https://github.com/mrmckeb/typescript-plugin-css-modules/issues/146#issuecomment-983069699)

**Comment by tleunen** [comment] 2022-12-06 16:25
I believe so, but I'm not entirely sure tbh.
I think it makes the file being "compiled" from the closest tsconfig, instead of being compiled from the root project in my case because even if each sub tsconfig inherits from the base one which contains the plugin, each `loadPaths` would need to be different imo, which is not great. I still can't seem to be able to do this for example and still require to use an absolute path to make it work.
```
"rendererOptions": {
            "sass": {
              "loadPaths": ["./"]
            }
          }
```

**Comment by falahati** [comment] 2022-12-06 16:29
but adding support for relative addresses still results in the same problem. the relative address has to be resolved against an absolute one and if the absolute address still changes per each `tsconfig`, then yeah, it is still going to be problematic. Not logically, but definitely in practice.

The problem is that we are trying to replicate the way WebPack resolves files with TS which isn't really ideal.

**Comment by tleunen** [comment] 2022-12-06 16:32
Ideally, it's resolved based on the absolute path where the config is in, not another tsconfig

**Comment by falahati** [comment] 2022-12-06 16:40
I am not very familiar with the typescript plugin API, but we currently use the `ts.server.PluginCreateInfo.getCurrentDirectory()` as the base path.

From your description, this returns the directory of each child's `tsconfig` file instead of the base file. I don't know if there is a way to fix it, or if there is, we really should.

@mrmckeb
