### ISSUE TITLE
Cannot work in .vue file

### ISSUE THREAD

**Issue by otomad** [mrmckeb/typescript-plugin-css-modules#187] opened 2022-12-09 15:12 UTC
### Describe the bug
It can be working properly in *.ts, *.tsx files, but cannot be working in *.vue files.

### Screenshots
![image](https://user-images.githubusercontent.com/56647156/206731831-0be56930-4e34-4333-b5e9-517a4ba087ed.png)
works fine in *.ts

![image](https://user-images.githubusercontent.com/56647156/206731876-7091945a-68e2-46ac-af97-dddc9a3b764f.png)
works fine in *.tsx

![image](https://user-images.githubusercontent.com/56647156/206732032-2ac6e2c5-0dcd-4bfb-9902-dc411fc1aeca.png)
cannot work in *.vue, detect as `Record<string, string>`.

### Desktop

- OS: Windows 11
- Browser: Edge, Chrome
- Version: 108.0.5359.99

### Additional context
One more thing, if enable VSCode extension **TypeScript Vue Plugin (Volar)**, it will conflict with typescript-plugin-css-modules, and crash the tsserver.

**Comment by mrmckeb** [comment] 2022-12-11 06:05
Hi there, are you able to provide a simple reproduction for me to test against? I don't work with Vue, but if you can provide a reproduction I should be able to find out what's happening!

**Comment by otomad** [comment] 2022-12-11 14:52
I opened a repository to [test typescript-plugin-css-modules in vue](https://github.com/otomad/test-typescript-plugin-css-modules-in-vue).

It works in  
\*.ts (/src/main.ts),  
\*.tsx (/src/components/MyJsx.tsx),

and doesn't work in  
\*.vue (/src/components/HelloWorld.vue).

And if VSCode extenstion [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin) is enabled, typescript-plugin-css-modules will not work either.

**Comment by mrmckeb** [comment] 2022-12-11 22:37
Thank you! I'll try to take a look this week.

**Comment by MichaelBitard** [comment] 2023-01-09 15:43
I think it has something to do with vue-tsc/volar.

See https://github.com/johnsoncodehk/volar/issues/1128 :cry:

**Comment by aradalvand** [comment] 2023-01-09 22:20
I'm having the same problem but for `.svelte` files, so this may something to do with VIte, perhaps — since Vite is the common denominator between Vue and SvelteKit.

@mrmckeb Any updates?

**Comment by aradalvand** [comment] 2023-01-10 00:45
@otomad Volar seems to have an option that lets you change the TypeScript version it uses under the hood; see if changing that to the workspace version fixes your problem.

Open up the command palette (Ctrl/CMD + Shift + P), and find the "Volar: Select TypeScript Version" item:

![image](https://user-images.githubusercontent.com/26527405/211436444-abfccd24-6833-463f-99d1-0642126a126d.png)

And then choose "Use workspace version":

![image](https://user-images.githubusercontent.com/26527405/211436497-da690d7f-247f-4efb-b5fd-6c544a9e697e.png)

**Comment by mrmckeb** [comment] 2023-02-18 08:52
Thanks @aradalvand! @otomad can you confirm that this suggestion solves your issue?

**Comment by otomad** [comment] 2023-02-23 07:50
> Thanks @aradalvand! @otomad can you confirm that this suggestion solves your issue?

No, it still doesn't work.

**Comment by mrmckeb** [comment] 2023-03-11 08:17
I've spent some time digging into this today, and it looks like this is not supported by Volar - as @MichaelBitard said.

Here the author's state that they don't support plugins:
https://github.com/vuejs/language-tools/issues/2153#issuecomment-1330606015

Here they detail why:
https://github.com/vuejs/language-tools/issues/1005#issuecomment-1420105858

I'll have to close this off for now sorry, but would love to help you if I could.

**Comment by mrmckeb** [comment] 2023-03-11 08:17
@aradalvand if you're still having issues with Svelte, please create a separate ticket/repro repo and I can dig in. It may be a similar issue, but I can investigate.

**Closed by mrmckeb** 2023-03-11 08:17 UTC
Labels: question

**Comment by otomad** [comment] 2023-03-11 08:21
Well, thank you very much anyway.
