### ISSUE TITLE
postcss nesting only works with '.' as nested class

### ISSUE THREAD

**Issue by odc-john** [mrmckeb/typescript-plugin-css-modules#118] opened 2021-04-11 10:02 UTC
**Describe the bug**

**To Reproduce**

vscode
```
  "typescript.tsserver.pluginPaths": ["typescript-plugin-css-modules"]
```

tsconfig
```
 {
        "name": "typescript-plugin-css-modules",
        "options": {
          "useConfig": true
        }
      }
```

postcss config
```
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-nested': {},
    'postcss-custom-media': {
      importFrom: __dirname + '/src/styles/variables/media.css'
    },
    // TODO: remove after demo
    // demo of css after minify. specifically merging media
    'postcss-pxtorem': {
      propList: ['*'],
      mediaQuery: true
    }
  }
};
```

Should be able to styles.TagBar. Only Tag shows
```
.Tag {
  position: relative;

  display: flex;
  width: 118px;
  height: 38px;

  color: var(--tag-color);

  background: var(--tag-bg);

  border-radius: 3px;

  &Bar {
    width: 4px;
    height: 100%;

    background: var(--tag-bar-bg);

    border-top-left-radius: 3px;
    border-bottom-left-radius: 3px;
  }

  &Label {
    display: flex;
    flex-grow: 1;
    align-items: center;
    justify-content: center;
    margin: 4px;

    font-weight: 500;
    font-size: 14px;
  }
}
```

Using '.' in nested shows styles.Bar
```
.Tag {
&.Bar {}
}
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrmckeb** [comment] 2021-04-22 07:27
Hi there, sorry for the slow reply.

Are you able to supply a reproduction repo? Just something very simple.

I can then take a look and hopefully fix this! I'm not 100% sure why this isn't working right now, but I'll do my best to get to the bottom of it :)

**Comment by IanVS** [comment] 2021-04-28 05:05
It seems that what you're trying to do is not permitted in the css nesting spec.  The nesting selector (`&`) is not as powerful as it is in SASS, as laid out in this comment: https://github.com/w3c/csswg-drafts/issues/2701#issuecomment-395260097.


Also, not that it helps, but I think there's a missing level for `postCssOptions` in your config. I believe it should be:

```
{
  "name": "typescript-plugin-css-modules",
  "options": {
    "postCssOptions": {
      "useConfig": true
    }
  }
}
```

**Comment by mrmckeb** [comment] 2021-04-28 07:45
Thanks for the help @IanVS - I didn't spot the options error myself, so great pickup!

I'll close this off, as it's very likely the cause. Please reopen if that doesn't help @odc-john!

**Closed by mrmckeb** 2021-04-28 07:45 UTC
