### ISSUE TITLE
`camelCase` option is not working

### ISSUE THREAD

**Issue by JounQin** [mrmckeb/typescript-plugin-css-modules#52] opened 2019-10-05 08:28 UTC
**Describe the bug**
As title, the generated definition is `{}`

**To Reproduce**

```jsonc
{
  "plugins": [
      {
        "name": "typescript-plugin-css-modules",
        "options": {
          "camelCase": "camelCase",
          "customMatcher": "\\.m\\.less$"
        }
      }
    ]
}
```

I've already have:
```ts
declare module '*.less' {
  const styles: Record<string, string>;
  export = styles;
}
```

and

```jsonc
// workspace `settings.json`
{
  "settings": {
    "typescript.tsdk": "node_modules/typescript/lib"
  }
}
```

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/8336744/66252319-c2bb4000-e78c-11e9-9143-59cff95cd87a.png)

**Desktop (please complete the following information):**

- OS: macOS Catalina

**Comment by mrmckeb** [comment] 2019-10-09 07:55
Hello @JounQin,

On Catalina already, you're very keen!

Are you able to share a repository with a reproduction? Even if it's a very simple case.

**Comment by mrmckeb** [comment] 2019-10-20 15:49
Hello, I've found the issue here, sorry for the inconvenience. It will be in the next release.

**Comment by mrmckeb** [comment] 2019-10-20 16:49
Hi @BasilPP, we've just released v2.0.0 which resolves this issue (the rule is now renamed to `classnameTransform`).

Release notes and migration steps can be found here: https://github.com/mrmckeb/typescript-plugin-css-modules/releases/tag/v2.0.0

Please let me know if you have any other issues or feedback! And thanks for your patience.

**Closed** 2019-10-20 16:49 UTC
Labels: question

**Comment by JounQin** [comment] 2019-10-20 23:03
@mrmckeb In the release page, it's named `localsConvention`?

**Comment by mrmckeb** [comment] 2019-10-21 06:58
Updated, thanks @JounQin - that was a mistake. It is meant to reflect the new `localsConvention`, but I named it `classnameTransform` because it is implemented separately and may not always be in-sync with that setting.
