### ISSUE TITLE
.module.scss files are being evaluated by ESLint in VS (not VSCode)

### ISSUE THREAD

**Issue by hellocontrol-bng** [mrmckeb/typescript-plugin-css-modules#64] opened 2019-11-23 01:12 UTC
**Describe the bug**
Enabling the plugin causes `.module.scss` files to be evaluated by eslint.

**To Reproduce**

1. Enable the plugin in tsconfig
2. Observe

**Observed behavior**
ESLint errors are displayed for the module.scss files even though they are not `js` or `ts` files

**Screenshots**
![image](https://user-images.githubusercontent.com/31326215/69470388-21437a00-0d4b-11ea-9ee5-437be1776b2e.png)

See TS errors that are happening in scss files

**Desktop (please complete the following information):**

- OS: Windows 10
- IDE: Visual Studio 2017 15.9.14

**Comment by mrmckeb** [comment] 2019-12-01 12:30
Hi @hellocontrol-bng, this doesn't happen in VSCode... so I'm not sure why you're seeing it.

Can you confirm your configuration for ESLint? It could be that you need to specify the file types supported (you do in VSCode - by default, it's `javascript` and `javascriptreact` only).

**Comment by mrmckeb** [comment] 2019-12-26 16:34
Hi @hellocontrol-bng - I just wanted to confirm if this issue could be closed? Thanks!

**Comment by hellocontrol-bng** [comment] 2019-12-27 23:08
I still encounter this, even without using .eslint - I tried with tslint and encounter the same issue. The issue goes away if I turn off this plugin. Is there anything I can do to help investigate?

**Comment by mrmckeb** [comment] 2019-12-30 09:45
As you're using VS and not VSCode, I'm not sure how to address this.

Have you tried editing your ESLint config to only target JavaScript and TypeScript files? Thats something you can set with the `files` key - I think that only works inside of `overrides`.

Does the VS ESLint plugin have any options? Maybe you can raise an issue there to see why this behaviour occurs?

**Comment by hellocontrol-bng** [comment] 2019-12-31 17:55
I have posted another version of the issue to the TSLint plugin, because that is what actually seems to be throwing the errors, even though it only does it when THIS plugin is also being used. For the record, I switched back to using TSLint and still see the issue, so I think it's something weird about that plugin. I'm not completely sure yet though, so I would like to see what they say.

I honestly don't know where to begin to debug it on my end because the tsserver.log files don't seem to show anything.

**Comment by mrmckeb** [comment] 2020-01-03 11:40
It's likely that the _imported_ files are being treated as JS/TS... which is not ideal. There could be a way to turn this off. Can you configure your plugins to target only specific file types?

I can see if there's anything we can do to fix that, but this doesn't happen in VSCode which again makes it hard to guess where the issue is. I'll keep thinking on it though.

**Comment by joeljeske** [comment] 2020-02-06 12:33
What if you used a custom renderer to add a comment to the files to turn off eslint?

/* eslint-disable */


If this works, this plugin should likely do it by default

**Comment by joeljeske** [comment] 2020-02-06 17:52
Pardon me, I was wrong in my assumption as to what the `customRenderer` was. My suggestion will not work. 

However, it might work if you used a newly proposed feature `customTypescriptTransformer` in #73

**Comment by mrmckeb** [comment] 2020-02-11 08:39
@hellocontrol-bng, is this issue still persisting for you? Were there any options on the ESLint plugin that helped?

**Comment by mrmckeb** [comment] 2020-02-28 09:06
@hellocontrol-bng, we've merged the work by @joeljeske and you can now use a (renamed) `customTemplate` to define output - and in the simplest case, you can add eslint-ignore to files.

Let us know if this does/doesn't help!

**Comment by mrmckeb** [comment] 2020-03-09 13:03
I'm closing this off, but feel free to reopen in future if needed.

**Closed by mrmckeb** 2020-03-09 13:03 UTC
Labels: question
